language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: joseamaita
  password:
    secure: DinuwjucmNmHoxkF8oSuifpVHBU2sSVgCYFXOsUzCgTX5K9UF41IYtdkYYA26P5NIhBMSmsTAA+8qHAYpP79Qk46f+2G5+y7nd6622NSVevA5tgcsBxTtbSMcT/OOeT8BLXfGMSDitDPcvbR6jsQcIM8g3HS50vnVQBvguL/eoBQ7h4ZnZcNj8ki9W+2v5vgoln2iZMCarkmrA+g9Viz2FxwhvLlGRVjbngT3QuqGOcf6/ny56OhTPyTuVFdI9r25mlJ/v/0qpYWPWuUf45NKCcj6rl71AFIVDYSP27OT0UHCAf8cq3R1TMUJ4qOIsYy2cNfVKnExwSXdc3m0+7o+8wm2/wEDNzAqwh7FTicJCFBV28WIYq12IzbEF5qmjJfbJ/fTymMrHa18BvkzDPMjc7eBiPxLzsvcFzwpPQXgu11UgmvYNCBXBKptmuoLQOAH6xkPbfxHAS2OW7rpDOcThpVpHhExTRdUK8cG9OTCP5kErqAKKekBmjRoKdHbhoHpuFTbZ/R1FeBI/knHaZlQFypSEDYmaAlUmWRJJddNj1Tepb+xSQoPtMipVuKHIDzWAI9BTGq/84cWVoaD9Gr+PTi2MRHsyhHTUuPnSFVMQUUTPLCyV6qxgmaxl16UxG2Ku9DQv5nLOAX7US3vyvqMGGwTonKteg15qSe4E9qu38=
  on:
    tags: true
    repo: joseamaita/toston
    python: 3.6
